DROP TABLE IF EXISTS report;
DROP TABLE IF EXISTS parse;

CREATE TABLE report (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  wcl_id TEXT NOT NULL,
  title TEXT NOT NULL,
  owner TEXT NOT NULL,
  start INTEGER NOT NULL,
  end INTEGER NOT NULL,
  zone INTEGER NOT NULL
);

CREATE TABLE parse (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  wcl_id INTEGER NOT NULL,
  start_time INTEGER NOT NULL,
  end_time INTEGER NOT NULL,
  boss TEXT NOT NULL,
  name TEXT NOT NULL,
);
